accepted = [
    "Apache-2.0",
    "MIT",
    "EUPL-1.2",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "CC0-1.0",
    "Unicode-3.0",
    "ISC",
    "Apache-2.0 WITH LLVM-exception",
    "NCSA",
    "bzip2-1.0.6",
]
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false
filter-noassertion = true
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "spirv-unknown-vulkan1.4",
]
