name: CI

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux_fetch_sources:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-docker-images: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'

      - uses: actions/checkout@v6

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-linux-nuke-15

      - name: Build Nuke
        shell: bash
        run: cargo xtask --nuke-versions 15.0 --fetch-nuke --limit-threads --target-platform linux

  linux:
    runs-on: ubuntu-latest
    needs: [linux_fetch_sources]
    container:
      image: quay.io/pypa/manylinux_2_28
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: ./scripts/devcontainer/linux/manylinux.sh

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-linux-nuke-15

      - name: Build Nuke
        shell: bash
        run: |
          source ~/.bashrc
          . "$HOME/.cargo/env"
          cargo xtask --compile --nuke-versions 15.0 --limit-threads --target-platform linux --output-to-package

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: nuke-linux
          path: package


  macos_aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-macos-nuke-15-16-aarch64

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 15.0,15.1,15.2,16.0 --limit-threads --target-platform macos-aarch64 --output-to-package

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-aarch64
          path: package


  macos_x86_64:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-macos-nuke-14-15-16-x86_64

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 14.0,14.1,15.0,15.1,15.2,16.0 --limit-threads --target-platform macos-x86-64 --output-to-package

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-aarch64
          path: package