name: CI

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: ./scripts/devcontainer/linux/manylinux.sh

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-linux-nuke-15

      - name: Build Nuke
        shell: bash
        run: |
          source ~/.bashrc
          . "$HOME/.cargo/env"
          cargo xtask --compile --nuke-versions 15.0 --limit-threads --target-platform linux

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: nuke-linux
          path: target/nuke/builds


  macos_aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-macos-nuke-15-16

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 15.0,15.1,15.2,16.0 --limit-threads --target-platform macos-aarch64

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-aarch64
          path: target/nuke/builds


  macos_x86_64:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-macos-nuke-15-16

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 14.0,14.1,15.0,15.1,15.2,16.0 --limit-threads --target-platform macos-x86-64

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-aarch64
          path: target/nuke/builds