name: CI

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - '*'
  pull_request:
  workflow_dispatch:

env:
  NUKE_VERSIONS: "15.0,15.1,15.2,16.0"

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-docker-images: "true"
          remove-codeql: "true"
          remove-haskell: "true"

      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Setup instance
        run: |
          sudo apt update
          sudo apt install protobuf-compiler -y
          cargo install --locked cargo-zigbuild

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - name: Build Nuke
        shell: bash
        run: |
          source ~/.bashrc
          cargo xtask --compile --nuke-versions ${{ env.NUKE_VERSIONS }} --limit-threads --target-platform linux --use-zig --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-linux
          path: package

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup instance
        run: choco install lessmsi protoc -y

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions ${{ env.NUKE_VERSIONS }} --limit-threads --target-platform windows --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-windows
          path: package

  macos:
    strategy:
      matrix:
        platform:
          - runner: macos-15-intel
            target: macos-x86-64
          - runner: macos-latest
            target: macos-aarch64

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions ${{ env.NUKE_VERSIONS }} --limit-threads --target-platform ${{ matrix.platform.target }} --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-${{ matrix.platform.target }}
          path: package

  release:
    runs-on: ubuntu-latest
    needs: [linux, windows, macos]
    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - uses: actions/download-artifact@v5
        with:
          path: package
          merge-multiple: true

      - name: Release
        run: cargo xtask --release-package --target-package-path ./target-package.zip
        env:
          GITHUB_RELEASE_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: target-package.zip
