name: CI

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    needs: [fetch_nuke_sources]
    container:
      image: quay.io/pypa/manylinux_2_28
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-docker-images: "true"
          remove-codeql: "true"
          remove-haskell: "true"


      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v6

      - name: Cache Nuke
        uses: actions/cache@v4
        with:
          path: target/nuke/deps
          key: cache-linux-nuke-16

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 16.0 --limit-threads --target-platform linux --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-linux
          path: package

  macos_aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-macos-nuke-15-16-aarch64

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 15.0,15.1,15.2,16.0 --limit-threads --target-platform macos-aarch64 --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-aarch64
          path: package

  macos:
    # matrix:
    #   matrix:
    #     version: [10, 12, 14]
    #     os: [ubuntu-latest, windows-latest]
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - name: Cache Nuke
        uses: actions/cache@v5
        with:
          path: target/nuke/deps
          key: cache-macos-x86_64-nuke-14-15-16

      - name: Build Nuke
        run: cargo xtask --compile --nuke-versions 14.0,14.1,15.0,15.1,15.2,16.0 --limit-threads --target-platform macos-x86-64 --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-macos-x86_64
          path: package

  release:
    runs-on: ubuntu-latest
    needs: [linux, macos_aarch64, macos_x86_64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v5
        with:
          path: package
          merge-multiple: true

      - run: ls -l && cd package && ls -l

      - name: Release
        run: cargo xtask --release-package --target-package-path ./target-package.zip

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: package
